
services:
  api:
    build: .
    container_name: tripnbond_api
    ports:
      - "8000:8000"
    volumes:
      # Espelha a pasta local para dentro do contêiner. 
      # Isso faz o --reload do uvicorn funcionar mesmo rodando no Docker!
      - .:/app
    environment:
      # Variáveis de ambiente que a API usará para conectar nos bancos
      - DATABASE_URL=postgresql://tripnbond_user:tripnbond_pass@postgres:5432/tripnbond_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    container_name: tripnbond_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tripnbond_user
      POSTGRES_PASSWORD: tripnbond_pass
      POSTGRES_DB: tripnbond_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: tripnbond_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  # Garante que os dados do banco e do cache não sejam apagados quando o contêiner parar
  postgres_data:
  redis_data: